# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from bs4 import Stylesheet


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 545)
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
       
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 727, 545))
        self.background.setAutoFillBackground(True)
        self.background.setFrameShape(QtWidgets.QFrame.Box)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background.gif"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(550, 490, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color:rgb(63, 126, 189);\n"
"\n"
"font: 75 8pt \"Malgun Gothic\";\n"
" color:rgb(255, 255, 255)")
        self.start.setFlat(False)
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(630, 490, 75, 23))
        self.stop.setStyleSheet("background-color:rgb(63, 126, 189);\n"
"\n"
"font: 75 8pt \"Malgun Gothic\";\n"
" color:rgb(255, 255, 255)")
        self.stop.setObjectName("stop")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
